import { Schema } from "koishi";
import type { MessageRecallSettings } from "./utils/messageRecall";
export interface Config {
    blockGroup: string[];
    adminId: string;
    wifeNameSeparator: string;
    wifeImageQuality: number;
    lpdaDateInterval: number;
    ntrOrdinal: number;
    ntrSwitchgear: boolean;
    ntrBlockGroup: string[];
    illustratedBook: boolean;
    divorceDateInterval: number;
    divorceLimit: number;
    divorceSwitchgear: boolean;
    divorceBlockGroup: string[];
    fuckWifeSwitchgear: boolean;
    kissWifeSwitchgear: boolean;
    dateWifeSwitchgear: boolean;
    fuckWifeCoolingTime: number;
    kissWifeCoolingTime: number;
    dateWifeCoolingTime: number;
    fuckWifeBlockGroup: string[];
    kissWifeBlockGroup: string[];
    dateWifeBlockGroup: string[];
    affectionCatastropheSwitchgear: boolean;
    affectionCatastropheProbability: number;
    affectionCatastropheBanSeconds: number;
    wifeAllOperationGroup: string[];
    wifeUploadGroup: string[];
    wifeUpdateGroup: string[];
    wifeDeleteGroup: string[];
    messageRecall: MessageRecallSettings;
}
export declare const ConfigSchema: Schema<Config>;
